name: CI

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Создание необходимых файлов
      - name: Create required files
        run: |
          # google-services.json для debug сборки
          mkdir -p app/src/debug
          echo "${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}" | base64 --decode > app/src/debug/google-services.json
          
          # local.properties с ключами
          echo "GEO_CODER_API_KEY=${{ secrets.GEO_CODER_API_KEY }}" > local.properties
          echo "MAPKIT_API_KEY=${{ secrets.MAPKIT_API_KEY }}" >> local.properties
          echo "sdk.dir=/usr/local/lib/android/sdk" >> local.properties

      # 2. Настройка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Используйте предустановленный SDK
      - name: Accept Android licenses
        run: |
          # Принимаем все лицензии автоматически
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null 2>&1
          echo "Android licenses accepted"

      # 4. Кэширование Gradle для ускорения сборок
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5. Детект (статический анализ кода)
      - name: Run Detekt
        run: |
          chmod +x ./gradlew
          ./gradlew detekt

      # 6. Юнит-тесты
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # 7. Сборка APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # 8. Загрузка на Firebase App Distribution
      - name: Upload to Firebase App Distribution
        if: success() && github.event.pull_request.head.repo.full_name == github.repository  # Только для PR из того же репозитория
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: app/src/debug/google-services.json
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: true